### ISSUE TITLE
Download a QGIS .qlr file for a layer

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#154]
Download a QGIS .qlr file for a layer so that it can easily be added into QGIS. This is the reverse of the QGIS Layer file upload tool. For an existing WMS/WFS/WCS layer we will allow the user to download a QGIS .qlr file that can be simply dragged and dropped into the user’s desktop QGIS session and the layer will appear in their layer list.  Implemented for QGIS backend only.

**Comment by boney-bun** [comment]
I'm still developing the backend.
But, I need to know if i'm on the right track.
What do you think of the UI @gubuntu @timlinux ?
![adddownloadqlr154](https://user-images.githubusercontent.com/4602383/29783140-7b561384-8c49-11e7-8b06-d5149a101fd2.gif)

**Comment by lucernae** [comment]
To elaborate the discussion from PR #317 I would like to extend the idea into a more detail execution.
@boney-bun, I think your proposed bussiness logic is inline with @gubuntu 's intention. I just would like to add some more details:

The bussiness logic/data flow would be:

Note that, checked item means that process were already implemented. Otherwise, it needs to be implemented.

# Upload Layer process

- [ ] User upload a layer (shapefile or tif). But there shouldn't be .qlr file on this. [geonode]
- [ ] Process Layer post_save signals to generate qgs project (with styles) [geonode.qgis_server]
- [ ] Receive request to generate qgs project and generate styles [otf-project]
- [ ] Generate .qgs file (styles and other information related with the layer is inside .qgs file) [otf-project]
- [ ] Add Link of qlr type in Layer post_save signals, after generating qgs project. This is just a process of adding a Link model with url to qgis-server backend that will be expected to server qlr download. No qlr generation actually happens here [geonode.qgis_server]

With that upload process a Link to a QLR project is established, and it will appear automatically in the Download Layer section.
Now, I assume that the QLR file @gubuntu meant is for QGIS Desktop user to add remote layer source to QGIS Server. CMIIW @gubuntu. So the QLR file needed to have datasource to a remote service (that particular geonode instance).
With this, we have some options:
- Provide WMS datasource connections for that layer in QLR file. This is possible at the moment. Useful for prototyping the concepts.
- Provide Geonode datasource connections. Geonode datasource connections is currently being developed by our QGIS team. @ismailsunni you need to provide us more insight on this. What kind of url datasource you need (and the format) to make this work.

# Download QLR process
- With the url provided in download QLR Link, do a redirect to qgis-server for that QLR request. [geonode.qgis_server]
- Process request of QLR file. Depending on the QLR output, we need to perhaps put some post process [otf-project]
   - If QGIS Server returned a local file datasource in the QLR file (I bet this is the case), we need to replace File path with URL to QGIS Server
- Depending on what the user would expect, replace the url in QLR file with either: datasource connection to WMS, or datasource connection to Geonode. [geonode.qgis_server]

**Comment by ismailsunni** [comment]
> Provide Geonode datasource connections. Geonode datasource connections is currently being developed by our QGIS team. @ismailsunni you need to provide us more insight on this. What kind of url datasource you need (and the format) to make this work.

We load WMS/WFS/XYZ layers to QGIS from a geonode connection. So, it's just normal WFS/WMS/XYZ layers.

**Comment by gubuntu** [comment]
The qtr must definitely reference just OGC services. Default to WMS and add WFS/WCS as options?

@lucernae I like your proposal to generate the qtr in layer upload post-save. @boney-bun are you handling this?

At the moment we need the quickest implementation since we have run out of time.

**Comment by timlinux** [comment]
See my comments in https://github.com/kartoza/geonode/issues/157#issuecomment-331687958 - similar things apply here:

* downloaded file must have a .qlr extension not .qlr.xml
* Layer name should be the same as GeoNode layer when the layer is added to the QGIS project

I wonder if we should also provide variants for WFS and XYZ layer files..... but above items more urgent....

**Comment by Gustry** [comment]
> Layer name should be the same as GeoNode layer when the layer is added to the QGIS project

I think it has been fixed yesterday by @boney-bun : https://github.com/kartoza/geonode/pull/337

> I wonder if we should also provide variants for WFS and XYZ layer files..... but above items more urgent....

I was thinking the same thing for the geonode client in QGIS, why not download the QLR from the client, so it will add the WFS link AND the style at the same time, no more copy/paste ...

**Comment by boney-bun** [comment]
@timlinux is it possible that .qlr.xml extension is specific to certain browsers?
i tried to download the .qlr file using chrome and safari. 
chrome returned .qlr, while safari gave .qlr.xml.

**Comment by gubuntu** [comment]
passed on testing except for #365
