### ISSUE TITLE
Image thumbnails are not generated when uploading a layer with management commands

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#195]
# Problem

I uploaded a raster layer with `python manage.py importlayers  -m directory_containing_data` and the layers that are generated have no thumbnails.

![thumbnails](https://cloud.githubusercontent.com/assets/2510900/25376630/366567fe-29a5-11e7-9cf4-9021c3a55115.png)

I then uploaded another raster layer using `python manage.py importlayers  -m directory_containing_data` and the layers generated have thumbnails

# Solution
Make it happy when using all conditions

child of #457

**Comment by lucernae** [comment]
I fixed wrong bbox and refactor thumbnail generation in #235 
However in staging, only nepal_buildings thumbnail can't be created. Currently investigates the issue

**Comment by boney-bun** [comment]
@NyakudyaA i tried to upload a layer stored in `/geonode_backups/layersToImports/` in the testing.

adding `-m` parameter will cause the layer failed to be imported.
however, if i ignore the `-m` parameter, the layer can be imported successfully.
see the GIF below for the steps i took:
![commandimportlayers](https://user-images.githubusercontent.com/4602383/44646336-d2524c00-aa04-11e8-8bda-15c8f726eb76.gif)

as the result, we can see this layer in testing: http://testing.geonode.kartoza.com/layers/geonode:hrsl_mdg_b1

then, i try to import another layer again from the same folder:
![commandimportlayers2](https://user-images.githubusercontent.com/4602383/44647293-db90e800-aa07-11e8-9a5f-83d99e0344fe.gif)

the end result is: 
http://testing.geonode.kartoza.com/layers/geonode:nepal_buildings

running the same thing on my local with `-m` parameter, i got this error message:
`There are no permissions for this object, setting default perms.`

i think this error message is because we didn't login to geonode before importing the layer. 
but, i'm not sure.
what metadata we would like to preserve when importing the layers with the management command?

**Comment by NyakudyaA** [comment]
@boney-bun cc @lucernae uploading layers with metadata are now fixed. I figured this out some time ago. This has to do with the encoding in the metadata.  I uploaded the layers and they all work. I will close this issue and hence you can look at the issues detailed in #496. 

NB: Production needs to be updated with staff that is working in staging
