### ISSUE TITLE
thumbnail and layer have different style

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#325]
The thumbnail for this (ephemeral) layer on the Rancher Geonode_QGIS-server have different styles: http://5.9.115.11/maps/8

My diagnosis is that each one was produced via a different QGIS project, each one applying its own random default style? 

Expected behaviour: a thumbnail has the same style as the layer at all times.

child of #457

**Comment by NyakudyaA** [comment]
We need to also consider the situation where a user creates a map using multiple layers. The thumbnail will be different in this case because it will consist of multiple layers and might need to be generated.

**Comment by boney-bun** [comment]
#472 preserve qml (if a user upload a qml) so that the style can be picked up when creating a thumbnail for a layer.
this issue has potentially  been addressed in #472

**Comment by lucernae** [comment]
Just a note here for reference. After some discussion with @boney-bun, we will use this approach:

1. All style definition (from QML) is stored on respective QGS project for layers. This is done in order to allow multiple styles definition for one layer. If user upload QML file, we will delete it from disk because it was stored on QGS file (and style body in database).
2. When we create new Map, we create a different QGS project for this map object. This will have empty style definition.
3. Get the default style definition from each layer registered to this map object (this is saved within the database).
4. Generate temporary QML file for each layer's default style from previous style definition. Put it on `qgis_layer` directory with the layer name prefix to associate it with a given layer.
5. Request `AddStyle` to QGIS Server Style Manager API of otf-project. This will consume each defined QML from each layer to particular map object's QGS Project. Each style will have name exactly like the layer name in order to avoid clashing style name.
6. Request `SetDefaultStyle` to QGIS Server Style Manager API of otf-project. This will set default style for each layer in map's QGS file.
7. Proceed to generate the thumbnail as usual, this time because QGS file defined the default style. It should pick up the corresponding style for each layer.

Expected Limitation/Behaviour:
1. After user created a Map object, it will generate a thumbnail. If user changed relevant layer style from layer detail view, it should not have any effect with the map's thumbnail. Map thumbnail should only be regenerated if user desired to do so from Map detail view.
2. Style used in thumbnail can be different with the style being showed by layers in Map detail view. This can only happen if after generating the thumbnail, user decided to change the style of individual layer from layer detail view. Because, Map detail view should always show default style of included layers there.

@gubuntu Does the expected limitation/behaviour above are acceptable?

**Comment by gubuntu** [comment]
yes @lucernae and @boney-bun that sounds perfect. very well described.

**Comment by NyakudyaA** [comment]
This is working properly for layers uploaded.
