### ISSUE TITLE
Applying new style does not work

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geonode#335]
# Problem
Uploading a style used to work and now it does not. 
![style](https://user-images.githubusercontent.com/2510900/30741673-08c7729e-9f96-11e7-8387-9d963421797c.png)

# Solution
Please fix as this is a regression

**Comment by lucernae** [comment]
I think the problem itself is because we didn't tell the user exactly what "style name" field expect.
This field were supposed to be filled with alphanumeric character (and underscore).
The functionality itself is okay, for example if you change into: `alternative_style` for Name field.

I will try to add more UI feedback on this.

**Comment by lucernae** [comment]
The UI Feedback will be something like this
<img width="712" alt="screen shot 2017-09-27 at 12 13 31" src="https://user-images.githubusercontent.com/831865/30896857-52682a52-a37d-11e7-918e-b92e0a6c5b23.png">
