### ISSUE TITLE
thumbnail disappears after editing metadata

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#388]
reported by @timlinux during Maputo workshop

child of #457

**Comment by NyakudyaA** [comment]
Tested this and thumbnail stays visible even after editing metadata. 

However, the legend disappears as illustrated below:
![health](https://user-images.githubusercontent.com/2510900/36251565-51bbdff4-124a-11e8-8cab-11d247e2b139.png)

After editing metadata
![legend](https://user-images.githubusercontent.com/2510900/36251591-62665596-124a-11e8-89a4-ca444df9baef.png)

Clicking on the legend icon to access the url results in the following:
![screenshot from 2018-02-15 12-20-10](https://user-images.githubusercontent.com/2510900/36251679-adb2a55e-124a-11e8-94fb-7d7398c2a852.png)

**Comment by boney-bun** [comment]
Hi @NyakudyaA 
could you test it again?
this issue seems to be no longer a problem.

![editmetadata](https://user-images.githubusercontent.com/4602383/44772990-93093400-ab99-11e8-97c7-2620c9a5c622.gif)

![editmetadata-2](https://user-images.githubusercontent.com/4602383/44772995-969cbb00-ab99-11e8-8360-dd5cf8291a2b.gif)

**Comment by gubuntu** [comment]
seems to be fixed. although the healthsites layer on testing did not have a thumbnail to start with. Setting it did generate a new one. I then edited its metadata and the thumbnail remained
