### ISSUE TITLE
Extend GeoNode to allow easily adding continually updated OSM exposure data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#422]
We aim to integrate docker-osm for this purpose. However, we are in discussions with Paolo Pasquali and the GeoNode community about existing documented techniques for OSM integration (http://docs.geonode.org/en/master/tutorials/advanced/adv_data_mgmt/osm.html) and will arrive at a solution that is best for the GeoNode project. The existing documented approach relies on GeoGig and Overpass queries so at this stage it is likely that we will add docker-osm as an option and use it in Mozambique because it can handle much larger downloads than Overpass and is already scheduled and in production elsewhere.

Allow user to configure or choose:
- area, based on a selection from another layer 
- feature types, with default Road and Building queries canned 

- must be part of Rancher orchestration
- add the resulting PostGIS layers to QGIS backend
- publish in GeoNode
- add metadata record with InaSAFE keywords or allow user to do so
- handle metadata updates as data changes
- handle passing layer to InaSAFE headless so it works in GeoSAFE
- thumbnails must update properly
- develop initially for QGIS server, but it must aso work with geoserver (see prototype in OONDRA)
- hande styilng: Upload styles to docker-osm layers? Either as postgis default styles or by applying via QGIS server API

child of #458

**Comment by gubuntu** [comment]
@lucernae @NyakudyaA let's keep it as simple as possible so it's quick to implement and easy to maintain. It only needs to be implemented at INGC but it's a bonus if it's also an optional part of the full stack GeoNode-QGIS orchestration. 

Consider these approaches to make it easy to pass the data and metadata to inasafe for analysis and to maintain the metadata through GeoNode:
- daily shapefile extract from postgis with pgsql2shp or ogr2ogr
- ogr or qgis virtual layer
-

**Comment by NyakudyaA** [comment]
@lucernae I have added the docker-osm to Mozambique geonode. So it will do a daily dump of all the shapefiles using the modified pg-backup
![osm-extracts](https://user-images.githubusercontent.com/2510900/46622469-043dee80-cb2b-11e8-87f9-c9c756e1a1be.png)

I think we need logic to rebuild the xyz  tilecache each night when the shapefiles are dumped. 
 Can you look at https://github.com/NyakudyaA/docker-pg-backup/tree/osm-extracts to see the logic for dumping the shapefile

**Comment by gubuntu** [comment]
looks like a great start @NyakudyaA

**Comment by NyakudyaA** [comment]
@gubuntu I will investigate and fix why they are not appearing in GeoSAFE and the thumbnail issue

**Comment by lucernae** [comment]
@gubuntu and @NyakudyaA for confirmation.

The plan would be to to reimport the shapefile generated by docker-osm stack. Reimport layers with overwrite=True will cause the cache to be cleaned and reapply thumbnail. We probably want to keep the metadata for this one so we will use the same metadata file for every import. Import will happen via Rancher cronjob schedule. The import task can be created with custom once-off rancher service. I was thinking this is not going to be included in the catalogue but we need to put the documentation somewhere because it was fairly easy to create it from Rancher interface in GeoSAFE stack.

Another interesting alternatives would be to use QLR definition with postgis connections inside to our pg osm containers. This will make the layer update by itself, although we still need to deal with the cache (clean periodically). I will try to see the possibility of running InaSAFE analysis with this kind of layer, but if it turns out to take too much time, I will drop it.

**Comment by NyakudyaA** [comment]
> @gubuntu I will investigate and fix why they are not appearing in GeoSAFE and the thumbnail issue

@gubuntu I have fixed the thumbnail and the layer now can be utilised in GeoSAFE
![screenshot 2018-10-19 at 14 25 32](https://user-images.githubusercontent.com/2510900/47218144-1fbabc00-d3ab-11e8-9384-c82348ad8786.png)

Layer in GeoSAFE
![screenshot 2018-10-19 at 14 28 31](https://user-images.githubusercontent.com/2510900/47218198-4a0c7980-d3ab-11e8-9548-af3aa418f4a6.png)

**Comment by gubuntu** [comment]
all sounds good @lucernae and @NyakudyaA

**Comment by lucernae** [comment]
The QLR Remote source upload has now been implemented and tested locally (against small layers). Now we just need to test it on testing, and implement daily tile seed refresh and bounds.

**Comment by NyakudyaA** [comment]
I have successfully added the layers in production. the seeding is also working in testing.
